### ISSUE TITLE
What are the default credentials for web authentication? 

### ISSUE THREAD

**Issue by Bedah2000** [theelims/FuckIO#2]
Hi,

i can´t figure out the right password and username for the web interface.
i tried 

user: FuckIO-c7d108f0
pass: smrtTHNG32

could you please help me?

Thanks
Peter

**Comment by theelims** [comment]
Hi Peter,

the default password is stored in the [config.h](/firmware/FuckIO/src/config.h) and can be adjusted to your liking. After first connection you're asked to give a new password for to administration interface and AP. 

For each connection to the admin interface your username is `admin` and the password you've set on the first run.

Please have a look at the user manual of [IoTWebConf](https://github.com/prampec/IotWebConf/blob/master/doc/UsersManual.md) for the expected behavior, also.

I hope this helps.

Cheers, 
elims
